### ISSUE TITLE
What editor are you making this in???????

### ISSUE THREAD

**Issue by Kingfrankbob** [uujuju1/poost#3]

**Comment by uujuju1** [comment]
not me
but drifted(12three7) did
i believe he did it on fl studio tho

**Comment by uujuju1** [comment]
my music that are here were made on lmms and ZynAddSubFx

**Comment by Kingfrankbob** [comment]
Nice, I was wondering what you used, since I use FL Studio, thanks!

**Comment by ghost** [comment]
> not me but drifted(12three7) did i believe he did it on fl studio tho

yeah, i made them (the music) in fl studio mobile.
